"""
Curated local mappings for fallback when external APIs fail.

CurAIos - Biological Data Curator Project Setup Script
Curaios is an AI-native metadata curation engine.
It transforms messy biomedical inputs into structured and normalized forms using LLMs.
Author: Rezwanuzzaman Laskar
Date: 2025
GitHub: https://github.com/rezwan-lab
"""

from typing import Dict, List, Any

# Local mappings for common organisms
# Format: {"user_input_variant": {"canonical_name": "...", "ncbi_taxonomy_id": int}}
ORGANISM_MAPPINGS = {
    "human": {"canonical_name": "Homo sapiens", "ncbi_taxonomy_id": 9606},
    "humans": {"canonical_name": "Homo sapiens", "ncbi_taxonomy_id": 9606},
    "homo sapiens": {"canonical_name": "Homo sapiens", "ncbi_taxonomy_id": 9606},
    "mouse": {"canonical_name": "Mus musculus", "ncbi_taxonomy_id": 10090},
    "mice": {"canonical_name": "Mus musculus", "ncbi_taxonomy_id": 10090},
    "mus musculus": {"canonical_name": "Mus musculus", "ncbi_taxonomy_id": 10090},
    "rat": {"canonical_name": "Rattus norvegicus", "ncbi_taxonomy_id": 10116},
    "rattus": {"canonical_name": "Rattus norvegicus", "ncbi_taxonomy_id": 10116},
    "rattus norvegicus": {"canonical_name": "Rattus norvegicus", "ncbi_taxonomy_id": 10116},
    "zebrafish": {"canonical_name": "Danio rerio", "ncbi_taxonomy_id": 7955},
    "danio": {"canonical_name": "Danio rerio", "ncbi_taxonomy_id": 7955},
    "danio rerio": {"canonical_name": "Danio rerio", "ncbi_taxonomy_id": 7955},
    "fruit fly": {"canonical_name": "Drosophila melanogaster", "ncbi_taxonomy_id": 7227},
    "drosophila": {"canonical_name": "Drosophila melanogaster", "ncbi_taxonomy_id": 7227},
    "drosophila melanogaster": {"canonical_name": "Drosophila melanogaster", "ncbi_taxonomy_id": 7227},
    "e coli": {"canonical_name": "Escherichia coli", "ncbi_taxonomy_id": 562},
    "e. coli": {"canonical_name": "Escherichia coli", "ncbi_taxonomy_id": 562},
    "ecoli": {"canonical_name": "Escherichia coli", "ncbi_taxonomy_id": 562},
    "escherichia coli": {"canonical_name": "Escherichia coli", "ncbi_taxonomy_id": 562},
    "yeast": {"canonical_name": "Saccharomyces cerevisiae", "ncbi_taxonomy_id": 4932},
    "s cerevisiae": {"canonical_name": "Saccharomyces cerevisiae", "ncbi_taxonomy_id": 4932},
    "s. cerevisiae": {"canonical_name": "Saccharomyces cerevisiae", "ncbi_taxonomy_id": 4932},
    "saccharomyces": {"canonical_name": "Saccharomyces cerevisiae", "ncbi_taxonomy_id": 4932},
    "saccharomyces cerevisiae": {"canonical_name": "Saccharomyces cerevisiae", "ncbi_taxonomy_id": 4932},
    "arabidopsis": {"canonical_name": "Arabidopsis thaliana", "ncbi_taxonomy_id": 3702},
    "a thaliana": {"canonical_name": "Arabidopsis thaliana", "ncbi_taxonomy_id": 3702},
    "a. thaliana": {"canonical_name": "Arabidopsis thaliana", "ncbi_taxonomy_id": 3702},
    "arabidopsis thaliana": {"canonical_name": "Arabidopsis thaliana", "ncbi_taxonomy_id": 3702},
    "c elegans": {"canonical_name": "Caenorhabditis elegans", "ncbi_taxonomy_id": 6239},
    "c. elegans": {"canonical_name": "Caenorhabditis elegans", "ncbi_taxonomy_id": 6239},
    "caenorhabditis": {"canonical_name": "Caenorhabditis elegans", "ncbi_taxonomy_id": 6239},
    "caenorhabditis elegans": {"canonical_name": "Caenorhabditis elegans", "ncbi_taxonomy_id": 6239},
    "worm": {"canonical_name": "Caenorhabditis elegans", "ncbi_taxonomy_id": 6239},
    "nematode": {"canonical_name": "Caenorhabditis elegans", "ncbi_taxonomy_id": 6239},
    "hiv": {"canonical_name": "Human immunodeficiency virus", "ncbi_taxonomy_id": 11676},
    "hiv-1": {"canonical_name": "Human immunodeficiency virus 1", "ncbi_taxonomy_id": 11676},
    "human immunodeficiency virus": {"canonical_name": "Human immunodeficiency virus", "ncbi_taxonomy_id": 11676},
    "sars-cov-2": {"canonical_name": "Severe acute respiratory syndrome coronavirus 2", "ncbi_taxonomy_id": 2697049},
    "sars cov 2": {"canonical_name": "Severe acute respiratory syndrome coronavirus 2", "ncbi_taxonomy_id": 2697049},
    "covid": {"canonical_name": "Severe acute respiratory syndrome coronavirus 2", "ncbi_taxonomy_id": 2697049},
    "covid-19": {"canonical_name": "Severe acute respiratory syndrome coronavirus 2", "ncbi_taxonomy_id": 2697049},
    "influenza": {"canonical_name": "Influenza virus", "ncbi_taxonomy_id": 11320},
    "flu virus": {"canonical_name": "Influenza virus", "ncbi_taxonomy_id": 11320},
    "influenza virus": {"canonical_name": "Influenza virus", "ncbi_taxonomy_id": 11320},
    "ebola": {"canonical_name": "Ebolavirus", "ncbi_taxonomy_id": 186536},
    "ebola virus": {"canonical_name": "Ebolavirus", "ncbi_taxonomy_id": 186536},
    "zika": {"canonical_name": "Zika virus", "ncbi_taxonomy_id": 64320},
    "zika virus": {"canonical_name": "Zika virus", "ncbi_taxonomy_id": 64320},
    "chicken": {"canonical_name": "Gallus gallus", "ncbi_taxonomy_id": 9031},
    "gallus": {"canonical_name": "Gallus gallus", "ncbi_taxonomy_id": 9031},
    "gallus gallus": {"canonical_name": "Gallus gallus", "ncbi_taxonomy_id": 9031},
    "pig": {"canonical_name": "Sus scrofa", "ncbi_taxonomy_id": 9823},
    "swine": {"canonical_name": "Sus scrofa", "ncbi_taxonomy_id": 9823},
    "sus scrofa": {"canonical_name": "Sus scrofa", "ncbi_taxonomy_id": 9823},
    "cow": {"canonical_name": "Bos taurus", "ncbi_taxonomy_id": 9913},
    "bovine": {"canonical_name": "Bos taurus", "ncbi_taxonomy_id": 9913},
    "bos taurus": {"canonical_name": "Bos taurus", "ncbi_taxonomy_id": 9913},
    "dog": {"canonical_name": "Canis lupus familiaris", "ncbi_taxonomy_id": 9615},
    "canine": {"canonical_name": "Canis lupus familiaris", "ncbi_taxonomy_id": 9615},
    "canis": {"canonical_name": "Canis lupus familiaris", "ncbi_taxonomy_id": 9615},
    "canis familiaris": {"canonical_name": "Canis lupus familiaris", "ncbi_taxonomy_id": 9615},
    "cat": {"canonical_name": "Felis catus", "ncbi_taxonomy_id": 9685},
    "feline": {"canonical_name": "Felis catus", "ncbi_taxonomy_id": 9685},
    "felis catus": {"canonical_name": "Felis catus", "ncbi_taxonomy_id": 9685},
    "rabbit": {"canonical_name": "Oryctolagus cuniculus", "ncbi_taxonomy_id": 9986},
    "oryctolagus": {"canonical_name": "Oryctolagus cuniculus", "ncbi_taxonomy_id": 9986},
    "oryctolagus cuniculus": {"canonical_name": "Oryctolagus cuniculus", "ncbi_taxonomy_id": 9986},
    "frog": {"canonical_name": "Xenopus laevis", "ncbi_taxonomy_id": 8355},
    "xenopus": {"canonical_name": "Xenopus laevis", "ncbi_taxonomy_id": 8355},
    "xenopus laevis": {"canonical_name": "Xenopus laevis", "ncbi_taxonomy_id": 8355},
    "macaque": {"canonical_name": "Macaca mulatta", "ncbi_taxonomy_id": 9544},
    "rhesus": {"canonical_name": "Macaca mulatta", "ncbi_taxonomy_id": 9544},
    "rhesus macaque": {"canonical_name": "Macaca mulatta", "ncbi_taxonomy_id": 9544},
    "macaca mulatta": {"canonical_name": "Macaca mulatta", "ncbi_taxonomy_id": 9544},
    "guinea pig": {"canonical_name": "Cavia porcellus", "ncbi_taxonomy_id": 10141},
    "cavia": {"canonical_name": "Cavia porcellus", "ncbi_taxonomy_id": 10141},
    "cavia porcellus": {"canonical_name": "Cavia porcellus", "ncbi_taxonomy_id": 10141},
    "sheep": {"canonical_name": "Ovis aries", "ncbi_taxonomy_id": 9940},
    "ovine": {"canonical_name": "Ovis aries", "ncbi_taxonomy_id": 9940},
    "ovis aries": {"canonical_name": "Ovis aries", "ncbi_taxonomy_id": 9940},
}

# Local mappings for common diseases
# Format: {"user_input_variant": {"canonical_name": "...", "mesh_id": "..."}}
DISEASE_MAPPINGS = {
    "alzheimer": {"canonical_name": "Alzheimer's Disease", "mesh_id": "D000544"},
    "alzheimer's": {"canonical_name": "Alzheimer's Disease", "mesh_id": "D000544"},
    "alzheimers": {"canonical_name": "Alzheimer's Disease", "mesh_id": "D000544"},
    "alzheimer's disease": {"canonical_name": "Alzheimer's Disease", "mesh_id": "D000544"},
    "ad": {"canonical_name": "Alzheimer's Disease", "mesh_id": "D000544"},
    "diabetes": {"canonical_name": "Diabetes Mellitus", "mesh_id": "D003920"},
    "diabetes mellitus": {"canonical_name": "Diabetes Mellitus", "mesh_id": "D003920"},
    "t1d": {"canonical_name": "Diabetes Mellitus, Type 1", "mesh_id": "D003922"},
    "type 1 diabetes": {"canonical_name": "Diabetes Mellitus, Type 1", "mesh_id": "D003922"},
    "t2d": {"canonical_name": "Diabetes Mellitus, Type 2", "mesh_id": "D003924"},
    "type 2 diabetes": {"canonical_name": "Diabetes Mellitus, Type 2", "mesh_id": "D003924"},
    "cancer": {"canonical_name": "Neoplasms", "mesh_id": "D009369"},
    "neoplasm": {"canonical_name": "Neoplasms", "mesh_id": "D009369"},
    "tumor": {"canonical_name": "Neoplasms", "mesh_id": "D009369"},
    "malignancy": {"canonical_name": "Neoplasms", "mesh_id": "D009369"},
    "breast cancer": {"canonical_name": "Breast Neoplasms", "mesh_id": "D001943"},
    "lung cancer": {"canonical_name": "Lung Neoplasms", "mesh_id": "D008175"},
    "colon cancer": {"canonical_name": "Colonic Neoplasms", "mesh_id": "D003110"},
    "colorectal cancer": {"canonical_name": "Colorectal Neoplasms", "mesh_id": "D015179"},
    "crc": {"canonical_name": "Colorectal Neoplasms", "mesh_id": "D015179"},
    "prostate cancer": {"canonical_name": "Prostatic Neoplasms", "mesh_id": "D011471"},
    "parkinson": {"canonical_name": "Parkinson Disease", "mesh_id": "D010300"},
    "parkinson's": {"canonical_name": "Parkinson Disease", "mesh_id": "D010300"},
    "parkinsons": {"canonical_name": "Parkinson Disease", "mesh_id": "D010300"},
    "parkinson's disease": {"canonical_name": "Parkinson Disease", "mesh_id": "D010300"},
    "pd": {"canonical_name": "Parkinson Disease", "mesh_id": "D010300"},
    "ms": {"canonical_name": "Multiple Sclerosis", "mesh_id": "D009103"},
    "multiple sclerosis": {"canonical_name": "Multiple Sclerosis", "mesh_id": "D009103"},
    "als": {"canonical_name": "Amyotrophic Lateral Sclerosis", "mesh_id": "D000690"},
    "amyotrophic lateral sclerosis": {"canonical_name": "Amyotrophic Lateral Sclerosis", "mesh_id": "D000690"},
    "hiv": {"canonical_name": "HIV Infections", "mesh_id": "D015658"},
    "hiv infection": {"canonical_name": "HIV Infections", "mesh_id": "D015658"},
    "covid": {"canonical_name": "COVID-19", "mesh_id": "D000086382"},
    "covid-19": {"canonical_name": "COVID-19", "mesh_id": "D000086382"},
    "covid19": {"canonical_name": "COVID-19", "mesh_id": "D000086382"},
    "coronavirus": {"canonical_name": "COVID-19", "mesh_id": "D000086382"},
    "asthma": {"canonical_name": "Asthma", "mesh_id": "D001249"},
    "copd": {"canonical_name": "Pulmonary Disease, Chronic Obstructive", "mesh_id": "D029424"},
    "chronic obstructive pulmonary disease": {"canonical_name": "Pulmonary Disease, Chronic Obstructive", "mesh_id": "D029424"},
    "ibd": {"canonical_name": "Inflammatory Bowel Diseases", "mesh_id": "D015212"},
    "inflammatory bowel disease": {"canonical_name": "Inflammatory Bowel Diseases", "mesh_id": "D015212"},
    "chd": {"canonical_name": "Coronary Heart Disease", "mesh_id": "D003327"},
    "coronary heart disease": {"canonical_name": "Coronary Heart Disease", "mesh_id": "D003327"},
    "hypertension": {"canonical_name": "Hypertension", "mesh_id": "D006973"},
    "high blood pressure": {"canonical_name": "Hypertension", "mesh_id": "D006973"},
    "heart failure": {"canonical_name": "Heart Failure", "mesh_id": "D006333"},
    "congestive heart failure": {"canonical_name": "Heart Failure", "mesh_id": "D006333"},
    "chf": {"canonical_name": "Heart Failure", "mesh_id": "D006333"},
    "stroke": {"canonical_name": "Stroke", "mesh_id": "D020521"},
    "cerebrovascular accident": {"canonical_name": "Stroke", "mesh_id": "D020521"},
    "cva": {"canonical_name": "Stroke", "mesh_id": "D020521"},
    "arthritis": {"canonical_name": "Arthritis", "mesh_id": "D001168"},
    "rheumatoid arthritis": {"canonical_name": "Arthritis, Rheumatoid", "mesh_id": "D001172"},
    "ra": {"canonical_name": "Arthritis, Rheumatoid", "mesh_id": "D001172"},
    "osteoarthritis": {"canonical_name": "Osteoarthritis", "mesh_id": "D010003"},
    "oa": {"canonical_name": "Osteoarthritis", "mesh_id": "D010003"},
    "autism": {"canonical_name": "Autism Spectrum Disorder", "mesh_id": "D000067877"},
    "asd": {"canonical_name": "Autism Spectrum Disorder", "mesh_id": "D000067877"},
    "autism spectrum disorder": {"canonical_name": "Autism Spectrum Disorder", "mesh_id": "D000067877"},
    "depression": {"canonical_name": "Depressive Disorder", "mesh_id": "D003866"},
    "major depression": {"canonical_name": "Depressive Disorder, Major", "mesh_id": "D003865"},
    "mdd": {"canonical_name": "Depressive Disorder, Major", "mesh_id": "D003865"},
    "anxiety": {"canonical_name": "Anxiety Disorders", "mesh_id": "D001008"},
    "anxiety disorder": {"canonical_name": "Anxiety Disorders", "mesh_id": "D001008"},
    "ptsd": {"canonical_name": "Stress Disorders, Post-Traumatic", "mesh_id": "D013313"},
    "post traumatic stress disorder": {"canonical_name": "Stress Disorders, Post-Traumatic", "mesh_id": "D013313"},
    "schizophrenia": {"canonical_name": "Schizophrenia", "mesh_id": "D012559"},
    "bipolar": {"canonical_name": "Bipolar Disorder", "mesh_id": "D001714"},
    "bipolar disorder": {"canonical_name": "Bipolar Disorder", "mesh_id": "D001714"},
    "obesity": {"canonical_name": "Obesity", "mesh_id": "D009765"},
    "metabolic syndrome": {"canonical_name": "Metabolic Syndrome", "mesh_id": "D024821"},
    "tuberculosis": {"canonical_name": "Tuberculosis", "mesh_id": "D014376"},
    "tb": {"canonical_name": "Tuberculosis", "mesh_id": "D014376"},
    "malaria": {"canonical_name": "Malaria", "mesh_id": "D008288"},
    "pneumonia": {"canonical_name": "Pneumonia", "mesh_id": "D011014"},
    "sepsis": {"canonical_name": "Sepsis", "mesh_id": "D018805"},
    "septicemia": {"canonical_name": "Sepsis", "mesh_id": "D018805"},
    "septic shock": {"canonical_name": "Shock, Septic", "mesh_id": "D012772"},
    "ckd": {"canonical_name": "Renal Insufficiency, Chronic", "mesh_id": "D051436"},
    "chronic kidney disease": {"canonical_name": "Renal Insufficiency, Chronic", "mesh_id": "D051436"},
    "liver disease": {"canonical_name": "Liver Diseases", "mesh_id": "D008107"},
    "cirrhosis": {"canonical_name": "Liver Cirrhosis", "mesh_id": "D008103"},
    "hepatitis": {"canonical_name": "Hepatitis", "mesh_id": "D006505"},
    "epilepsy": {"canonical_name": "Epilepsy", "mesh_id": "D004827"},
    "seizure disorder": {"canonical_name": "Epilepsy", "mesh_id": "D004827"},
    "migraine": {"canonical_name": "Migraine Disorders", "mesh_id": "D008881"},
    "migraine headache": {"canonical_name": "Migraine Disorders", "mesh_id": "D008881"},
    "leukemia": {"canonical_name": "Leukemia", "mesh_id": "D007938"},
    "lymphoma": {"canonical_name": "Lymphoma", "mesh_id": "D008223"},
    "glioblastoma": {"canonical_name": "Glioblastoma", "mesh_id": "D005909"},
    "gbm": {"canonical_name": "Glioblastoma", "mesh_id": "D005909"},
    "glioma": {"canonical_name": "Glioma", "mesh_id": "D005910"},
}

# Local mappings for data types
# Format: {"user_input_variant": {"canonical_name": "..."}}
DATA_TYPE_MAPPINGS = {
    "rna-seq": {"canonical_name": "RNAseq"},
    "rna seq": {"canonical_name": "RNAseq"},
    "rnaseq": {"canonical_name": "RNAseq"},
    "rna sequencing": {"canonical_name": "RNAseq"},
    "transcriptomics": {"canonical_name": "RNAseq"},
    "transcriptome sequencing": {"canonical_name": "RNAseq"},
    "single cell": {"canonical_name": "scRNAseq"},
    "single-cell": {"canonical_name": "scRNAseq"},
    "scrna-seq": {"canonical_name": "scRNAseq"},
    "single cell rna seq": {"canonical_name": "scRNAseq"},
    "sc-rna-seq": {"canonical_name": "scRNAseq"},
    "single cell sequencing": {"canonical_name": "scRNAseq"},
    "single cell transcriptomics": {"canonical_name": "scRNAseq"},
    "microarray": {"canonical_name": "Microarray"},
    "array": {"canonical_name": "Microarray"},
    "expression array": {"canonical_name": "Microarray"},
    "gene expression array": {"canonical_name": "Microarray"},
    "chip": {"canonical_name": "Microarray"},
    "wgs": {"canonical_name": "WGS"},
    "whole genome sequencing": {"canonical_name": "WGS"},
    "genome sequencing": {"canonical_name": "WGS"},
    "complete genome": {"canonical_name": "WGS"},
    "whole exome sequencing": {"canonical_name": "WES"},
    "exome sequencing": {"canonical_name": "WES"},
    "exome": {"canonical_name": "WES"},
    "wes": {"canonical_name": "WES"},
    "atac-seq": {"canonical_name": "ATAC-seq"},
    "atac seq": {"canonical_name": "ATAC-seq"},
    "atacseq": {"canonical_name": "ATAC-seq"},
    "chromatin accessibility": {"canonical_name": "ATAC-seq"},
    "chip-seq": {"canonical_name": "ChIP-seq"},
    "chip seq": {"canonical_name": "ChIP-seq"},
    "chipseq": {"canonical_name": "ChIP-seq"},
    "chromatin immunoprecipitation": {"canonical_name": "ChIP-seq"},
    "proteomics": {"canonical_name": "Proteomics"},
    "mass spectrometry": {"canonical_name": "Proteomics"},
    "ms/ms": {"canonical_name": "Proteomics"},
    "protein expression": {"canonical_name": "Proteomics"},
    "proteome": {"canonical_name": "Proteomics"},
    "metabolomics": {"canonical_name": "Metabolomics"},
    "metabolite profiling": {"canonical_name": "Metabolomics"},
    "metabolite analysis": {"canonical_name": "Metabolomics"},
    "metabolome": {"canonical_name": "Metabolomics"},
    "metagenomics": {"canonical_name": "Metagenomics"},
    "metagenomic sequencing": {"canonical_name": "Metagenomics"},
    "microbiome sequencing": {"canonical_name": "Metagenomics"},
    "microbiome analysis": {"canonical_name": "Metagenomics"},
    "16s": {"canonical_name": "Metagenomics"},
    "16s rrna": {"canonical_name": "Metagenomics"},
    "16s sequencing": {"canonical_name": "Metagenomics"},
    "bisulfite sequencing": {"canonical_name": "BS-seq"},
    "bs-seq": {"canonical_name": "BS-seq"},
    "bisulfite": {"canonical_name": "BS-seq"},
    "methylation sequencing": {"canonical_name": "BS-seq"},
    "dna methylation": {"canonical_name": "BS-seq"},
    "wgbs": {"canonical_name": "BS-seq"},
    "whole genome bisulfite": {"canonical_name": "BS-seq"},
    "rna-seq": {"canonical_name": "RNAseq"},
    "rna-seq": {"canonical_name": "RNAseq"},
    "bulk rna-seq": {"canonical_name": "RNAseq"},
    "bulk rnaseq": {"canonical_name": "RNAseq"},
    "hi-c": {"canonical_name": "Hi-C"},
    "hic": {"canonical_name": "Hi-C"},
    "chromosome conformation": {"canonical_name": "Hi-C"},
    "3d genomics": {"canonical_name": "Hi-C"},
    "spatial transcriptomics": {"canonical_name": "Spatial-seq"},
    "spatial-seq": {"canonical_name": "Spatial-seq"},
    "spatial": {"canonical_name": "Spatial-seq"},
    "visium": {"canonical_name": "Spatial-seq"},
    "10x visium": {"canonical_name": "Spatial-seq"},
    "slide-seq": {"canonical_name": "Spatial-seq"},
    "slideseq": {"canonical_name": "Spatial-seq"},
    "cytof": {"canonical_name": "CyTOF"},
    "mass cytometry": {"canonical_name": "CyTOF"},
    "flow cytometry": {"canonical_name": "Flow Cytometry"},
    "facs": {"canonical_name": "Flow Cytometry"},
    "flow": {"canonical_name": "Flow Cytometry"},
    "snp array": {"canonical_name": "SNP Array"},
    "genotyping array": {"canonical_name": "SNP Array"},
    "gwas": {"canonical_name": "SNP Array"},
    "genotyping": {"canonical_name": "SNP Array"},
    "snp": {"canonical_name": "SNP Array"},
    "clinical": {"canonical_name": "Clinical Data"},
    "clinical data": {"canonical_name": "Clinical Data"},
    "patient data": {"canonical_name": "Clinical Data"},
    "electronic health record": {"canonical_name": "Clinical Data"},
    "ehr": {"canonical_name": "Clinical Data"},
    "emr": {"canonical_name": "Clinical Data"},
    "imaging": {"canonical_name": "Imaging"},
    "radiology": {"canonical_name": "Imaging"},
    "mri": {"canonical_name": "Imaging"},
    "ct scan": {"canonical_name": "Imaging"},
    "pet": {"canonical_name": "Imaging"},
    "histology": {"canonical_name": "Histology"},
    "histopathology": {"canonical_name": "Histology"},
    "pathology": {"canonical_name": "Histology"},
    "ihc": {"canonical_name": "Histology"},
    "immunohistochemistry": {"canonical_name": "Histology"},
    "small rna-seq": {"canonical_name": "Small RNA-seq"},
    "mirna-seq": {"canonical_name": "Small RNA-seq"},
    "mirna": {"canonical_name": "Small RNA-seq"},
    "micrornas": {"canonical_name": "Small RNA-seq"},
    "nanopore": {"canonical_name": "Nanopore Sequencing"},
    "oxford nanopore": {"canonical_name": "Nanopore Sequencing"},
    "long-read sequencing": {"canonical_name": "Long-read Sequencing"},
    "pacbio": {"canonical_name": "Long-read Sequencing"},
    "smrt": {"canonical_name": "Long-read Sequencing"},
    "iso-seq": {"canonical_name": "Iso-Seq"},
    "isoseq": {"canonical_name": "Iso-Seq"},
    "isoform sequencing": {"canonical_name": "Iso-Seq"},
    "full-length transcriptome": {"canonical_name": "Iso-Seq"},
    "chip-chip": {"canonical_name": "ChIP-chip"},
    "chip on chip": {"canonical_name": "ChIP-chip"},
    "protein microarray": {"canonical_name": "Protein Microarray"},
    "proteomic array": {"canonical_name": "Protein Microarray"}
}

# Experimental technique platform mappings
# Format: {"user_input_variant": {"canonical_name": "..."}}
PLATFORM_MAPPINGS = {
    "illumina": {"canonical_name": "Illumina"},
    "hiseq": {"canonical_name": "Illumina HiSeq"},
    "nextseq": {"canonical_name": "Illumina NextSeq"},
    "novaseq": {"canonical_name": "Illumina NovaSeq"},
    "miseq": {"canonical_name": "Illumina MiSeq"},
    "iseq": {"canonical_name": "Illumina iSeq"},
    "miniseq": {"canonical_name": "Illumina MiniSeq"},
    "pacbio": {"canonical_name": "PacBio"},
    "sequel": {"canonical_name": "PacBio Sequel"},
    "smrt": {"canonical_name": "PacBio SMRT"},
    "nanopore": {"canonical_name": "Oxford Nanopore"},
    "promethion": {"canonical_name": "Oxford Nanopore PromethION"},
    "minion": {"canonical_name": "Oxford Nanopore MinION"},
    "gridion": {"canonical_name": "Oxford Nanopore GridION"},
    "10x": {"canonical_name": "10x Genomics"},
    "10x genomics": {"canonical_name": "10x Genomics"},
    "chromium": {"canonical_name": "10x Genomics Chromium"},
    "affymetrix": {"canonical_name": "Affymetrix"},
    "agilent": {"canonical_name": "Agilent"},
    "thermo": {"canonical_name": "Thermo Fisher"},
    "thermofisher": {"canonical_name": "Thermo Fisher"},
    "ion torrent": {"canonical_name": "Ion Torrent"},
    "iontorrent": {"canonical_name": "Ion Torrent"},
    "ion": {"canonical_name": "Ion Torrent"},
    "proton": {"canonical_name": "Ion Torrent Proton"},
    "s5": {"canonical_name": "Ion Torrent S5"},
    "mgiseq": {"canonical_name": "MGI"},
    "mgi": {"canonical_name": "MGI"},
    "bgi": {"canonical_name": "BGI"},
    "dnbseq": {"canonical_name": "MGI DNBSEQ"},
    "complete genomics": {"canonical_name": "Complete Genomics"},
    "roche": {"canonical_name": "Roche"},
    "454": {"canonical_name": "Roche 454"},
    "pyrosequencing": {"canonical_name": "Roche 454"},
    "gs flx": {"canonical_name": "Roche 454 GS FLX"},
    "solid": {"canonical_name": "SOLiD"},
    "abi solid": {"canonical_name": "SOLiD"},
    "applied biosystems": {"canonical_name": "Applied Biosystems"},
    "abi": {"canonical_name": "Applied Biosystems"},
    "qiagen": {"canonical_name": "QIAGEN"},
    "genechip": {"canonical_name": "Affymetrix GeneChip"},
    "genepix": {"canonical_name": "GenePix"},
    "nanostring": {"canonical_name": "NanoString"},
    "luminex": {"canonical_name": "Luminex"},
    "fluidigm": {"canonical_name": "Fluidigm"},
    "c1": {"canonical_name": "Fluidigm C1"},
    "biomark": {"canonical_name": "Fluidigm Biomark"},
    "helicos": {"canonical_name": "Helicos"},
    "heliscope": {"canonical_name": "Helicos HeliScope"},
    "dropseq": {"canonical_name": "Drop-seq"},
    "smart-seq": {"canonical_name": "SMART-seq"},
    "smartseq": {"canonical_name": "SMART-seq"},
    "smart-seq2": {"canonical_name": "SMART-seq2"},
    "cel-seq": {"canonical_name": "CEL-seq"},
    "celseq": {"canonical_name": "CEL-seq"},
    "indrops": {"canonical_name": "inDrops"},
    "mars-seq": {"canonical_name": "MARS-seq"},
    "marsseq": {"canonical_name": "MARS-seq"},
    "thermo cycler": {"canonical_name": "Thermo Cycler"},
    "qpcr": {"canonical_name": "qPCR"},
    "rt-qpcr": {"canonical_name": "RT-qPCR"},
    "realtime pcr": {"canonical_name": "qPCR"},
    "real-time pcr": {"canonical_name": "qPCR"},
    "ddpcr": {"canonical_name": "ddPCR"},
    "digital pcr": {"canonical_name": "ddPCR"},
    "digital droplet pcr": {"canonical_name": "ddPCR"}
}

# Disease stage and severity mappings
# Format: {"user_input_variant": {"canonical_name": "..."}}
DISEASE_STAGE_MAPPINGS = {
    "early": {"canonical_name": "Early Stage"},
    "early stage": {"canonical_name": "Early Stage"},
    "early onset": {"canonical_name": "Early Onset"},
    "late": {"canonical_name": "Late Stage"},
    "late stage": {"canonical_name": "Late Stage"},
    "late onset": {"canonical_name": "Late Onset"},
    "advanced": {"canonical_name": "Advanced Stage"},
    "terminal": {"canonical_name": "Terminal Stage"},
    "mild": {"canonical_name": "Mild"},
    "moderate": {"canonical_name": "Moderate"},
    "severe": {"canonical_name": "Severe"},
    "acute": {"canonical_name": "Acute"},
    "chronic": {"canonical_name": "Chronic"},
    "relapsing": {"canonical_name": "Relapsing"},
    "remitting": {"canonical_name": "Remitting"},
    "relapsing-remitting": {"canonical_name": "Relapsing-Remitting"},
    "progressive": {"canonical_name": "Progressive"},
    "primary progressive": {"canonical_name": "Primary Progressive"},
    "secondary progressive": {"canonical_name": "Secondary Progressive"},
    "metastatic": {"canonical_name": "Metastatic"},
    "metastasis": {"canonical_name": "Metastatic"},
    "recurrent": {"canonical_name": "Recurrent"},
    "refractory": {"canonical_name": "Refractory"},
    "resistant": {"canonical_name": "Resistant"},
    "asymptomatic": {"canonical_name": "Asymptomatic"},
    "presymptomatic": {"canonical_name": "Presymptomatic"},
    "prodromal": {"canonical_name": "Prodromal"},
    "remission": {"canonical_name": "Remission"},
    "stage i": {"canonical_name": "Stage I"},
    "stage 1": {"canonical_name": "Stage I"},
    "stage ii": {"canonical_name": "Stage II"},
    "stage 2": {"canonical_name": "Stage II"},
    "stage iii": {"canonical_name": "Stage III"},
    "stage 3": {"canonical_name": "Stage III"},
    "stage iv": {"canonical_name": "Stage IV"},
    "stage 4": {"canonical_name": "Stage IV"},
    "grade 1": {"canonical_name": "Grade 1"},
    "grade 2": {"canonical_name": "Grade 2"},
    "grade 3": {"canonical_name": "Grade 3"},
    "grade 4": {"canonical_name": "Grade 4"},
    "low grade": {"canonical_name": "Low Grade"},
    "high grade": {"canonical_name": "High Grade"},
    "well differentiated": {"canonical_name": "Well Differentiated"},
    "moderately differentiated": {"canonical_name": "Moderately Differentiated"},
    "poorly differentiated": {"canonical_name": "Poorly Differentiated"},
    "undifferentiated": {"canonical_name": "Undifferentiated"}
}

# Sample type mappings
# Format: {"user_input_variant": {"canonical_name": "..."}}
SAMPLE_TYPE_MAPPINGS = {
    "tissue": {"canonical_name": "Tissue"},
    "blood": {"canonical_name": "Blood"},
    "plasma": {"canonical_name": "Plasma"},
    "serum": {"canonical_name": "Serum"},
    "urine": {"canonical_name": "Urine"},
    "csf": {"canonical_name": "Cerebrospinal Fluid"},
    "cerebrospinal fluid": {"canonical_name": "Cerebrospinal Fluid"},
    "saliva": {"canonical_name": "Saliva"},
    "stool": {"canonical_name": "Stool"},
    "feces": {"canonical_name": "Stool"},
    "fecal": {"canonical_name": "Stool"},
    "biopsy": {"canonical_name": "Biopsy"},
    "cell line": {"canonical_name": "Cell Line"},
    "cell culture": {"canonical_name": "Cell Culture"},
    "primary cell": {"canonical_name": "Primary Cell"},
    "pbmc": {"canonical_name": "PBMC"},
    "peripheral blood mononuclear cell": {"canonical_name": "PBMC"},
    "bone marrow": {"canonical_name": "Bone Marrow"},
    "tumor": {"canonical_name": "Tumor"},
    "tumor tissue": {"canonical_name": "Tumor"},
    "normal tissue": {"canonical_name": "Normal Tissue"},
    "adjacent normal": {"canonical_name": "Adjacent Normal Tissue"},
    "normal adjacent": {"canonical_name": "Adjacent Normal Tissue"},
    "ffpe": {"canonical_name": "FFPE"},
    "formalin fixed": {"canonical_name": "FFPE"},
    "formalin-fixed": {"canonical_name": "FFPE"},
    "fresh frozen": {"canonical_name": "Fresh Frozen"},
    "frozen tissue": {"canonical_name": "Fresh Frozen"},
    "snap frozen": {"canonical_name": "Fresh Frozen"},
    "organoid": {"canonical_name": "Organoid"},
    "spheroid": {"canonical_name": "Spheroid"},
    "xenograft": {"canonical_name": "Xenograft"},
    "pdx": {"canonical_name": "PDX"},
    "patient derived xenograft": {"canonical_name": "PDX"},
    "exosome": {"canonical_name": "Exosome"},
    "extracellular vesicle": {"canonical_name": "Extracellular Vesicle"},
    "ev": {"canonical_name": "Extracellular Vesicle"},
    "cfDNA": {"canonical_name": "cfDNA"},
    "cf-dna": {"canonical_name": "cfDNA"},
    "cell free dna": {"canonical_name": "cfDNA"},
    "cell-free dna": {"canonical_name": "cfDNA"},
    "ctDNA": {"canonical_name": "ctDNA"},
    "ct-dna": {"canonical_name": "ctDNA"},
    "circulating tumor dna": {"canonical_name": "ctDNA"},
    "circulating-tumor dna": {"canonical_name": "ctDNA"},
    "cfdna": {"canonical_name": "cfDNA"},
    "ctc": {"canonical_name": "CTC"},
    "circulating tumor cell": {"canonical_name": "CTC"}
}